name: Tests in Docker container

on:
  push:
    branches: [master]
jobs:
  test_run:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Run the build process with Docker
      uses: addnab/docker-run-action@v3
        with:
            image: olegtron228/olegtron:v4
