name: Tests in Docker container

on:
  push:
    branches: [master]
jobs:
  test_run:
    runs-on: ubuntu-latest
    container: olegtron228/olegtron:v4
    steps:
      - run: npm run test_all_headless

