name: Tests in Docker container
on: 
    push:
        branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: olegtron228/olegtron:v4
      options: --shm-size=4gb
    steps:
      - name: Run tests
        run: cd /app && npm run test_all_headless